TexturePath = "textures/"
LevelPath = "lvl/"
Version = "v1.5"
Title = "Tk´s Adventure"
RenderLayers = 70
TPS = 44
FPS = 60
TileSize = 56
DrawCollision = False
levels = ["teststage.lvl", "JumpAndRun.lvl", "EMPTY.lvl"]
Debug = True
x_w_off = 5  # World tile Load offset (shouldnt be changed!)
y_w_off = 2  # World tile Load offset (shouldnt be changed!)